name = "Makeshift SMP"
author = "ThaMaTTeR"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd4f430dd1662810869bd918154ef29a1993564ec39ca72a4097d5fabc8bcb06"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.223"
