name = "Makeshift SMP"
author = "ThaMaTTeR"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a4bb2700b38c126c0e986860ca39166b577a6ea783b79e9f429779e3d458733"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.223"
