name = "Makeshift SMP"
author = "ThaMaTTeR"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b8362dcc45cc3ba1850690bad6411074bca4b8e8376810669d1c3aec6c02748"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.223"
